# Generated by Django 3.1.14 on 2022-11-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0004_auto_20221108_1930"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
